### ISSUE TITLE
[SP-118] 받은 호감 수락 API 명세서 작성

### ISSUE THREAD

**Issue by smc2315** [SWM-Cupid/jikting-backend#22]
## Jira Issue

[SP-118](https://soma-cupid.atlassian.net/browse/SP-118?atlOrigin=eyJpIjoiOWI1NTEwMmFiMTY5NDYwMTk0MGU4NTQ1MGNjOTFlZTQiLCJwIjoiaiJ9)

## 요구사항

- [ ] 받은 호감 수락 성공 API 명세서 작성
- [ ] 받은 호감 수락 실패 API 명세서 작성

[SP-118]: https://soma-cupid.atlassian.net/browse/SP-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jeongyuneo** [comment]
[고민한 내용](https://jeongyuneo.notion.site/api-c90b7b832235405dbebffb448b987af0?pvs=4)
